In [1]:
import pandas as pd
import numpy as num
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore')
%matplotlib inline


In [2]:
data = pd.read_csv('Zomato-data-.csv')

In [5]:
data

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining


In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    object
 4   votes                        148 non-null    int64 
 5   approx_cost(for two people)  148 non-null    int64 
 6   listed_in(type)              148 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.2+ KB


In [9]:
data.isna().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
approx_cost(for two people)    0
listed_in(type)                0
dtype: int64

In [11]:
data.dropna(inplace=True)

In [13]:
data.describe(include='O').T

,count,unique,top,freq
name,148,145,San Churro Cafe,2
online_order,148,2,No,90
book_table,148,2,No,140
rate,148,20,3.8/5,19
listed_in(type),148,4,Dining,110


In [15]:
data['online_order'].unique()

array(['Yes', 'No'], dtype=object)

In [17]:
data['book_table'].unique()

array(['Yes', 'No'], dtype=object)

In [19]:
data.replace({'online_order':{'Yes':0,'No':1}},inplace=True)
data.replace({'book_table':{'Yes':0,'No':1}},inplace=True)

In [21]:
data['online_order']

0      0
1      0
2      0
3      1
4      1
      ..
143    1
144    1
145    0
146    1
147    0
Name: online_order, Length: 148, dtype: int64

In [23]:
data.describe(include='O').T

,count,unique,top,freq
name,148,145,San Churro Cafe,2
rate,148,20,3.8/5,19
listed_in(type),148,4,Dining,110


In [25]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [27]:
le = LabelEncoder()

In [29]:
data.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes',
       'approx_cost(for two people)', 'listed_in(type)'],
      dtype='object')

In [31]:
for i in ['name','rate','listed_in(type)']:
    data[i] = le.fit_transform(data[i])
    

In [33]:
data.rename(columns={'approx_cost(for two people)':'approx cost'},inplace=True)

In [35]:
sc = StandardScaler()

In [37]:
SF = sc.fit_transform(data[['approx cost','votes']])

In [39]:
SF

array([[ 1.71707143,  0.78314156],
       [ 1.71707143,  0.80156158],
       [ 1.71707143,  1.00264688],
       [-0.53183628, -0.27140499],
       [ 0.81750835, -0.15167482],
       [ 0.81750835,  0.03252545],
       [ 1.71707143, -0.39420517],
       [ 0.81750835,  3.51698058],
       [ 1.26728989,  0.09085554],
       [ 0.59261757,  0.36715595],
       [ 0.3677268 ,  0.21058572],
       [ 0.81750835, -0.17623485],
       [ 0.3677268 , -0.15474482],
       [ 0.14283603,  0.24435576],
       [ 1.71707143,  1.00264688],
       [ 1.04239912, -0.26833499],
       [ 1.71707143, -0.20232989],
       [ 1.26728989, -0.18544487],
       [-0.53183628, -0.26372998],
       [-0.08205474, -0.38653016],
       [-0.08205474, -0.31131505],
       [ 0.3677268 , -0.13018479],
       [ 2.16685298, -0.36350513],
       [ 0.81750835, -0.31131505],
       [-0.53183628, -0.35890012],
       [ 0.81750835, -0.38960017],
       [-0.98161783, -0.29136002],
       [ 0.3677268 , -0.40034518],
       [ 0.59261757,

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             148 non-null    int32
 1   online_order     148 non-null    int64
 2   book_table       148 non-null    int64
 3   rate             148 non-null    int32
 4   votes            148 non-null    int64
 5   approx cost      148 non-null    int64
 6   listed_in(type)  148 non-null    int32
dtypes: int32(3), int64(4)
memory usage: 6.5 KB


In [44]:
X_cls = data.drop('online_order',axis=1)
y_cls = data['online_order'] 

In [46]:
X_reg = data.drop('approx cost',axis=1)
y_reg = data['approx cost'] 

In [48]:
X_cls

,name,book_table,rate,votes,approx cost,listed_in(type)
0,59,0,15,775,800,0
1,113,1,15,787,800,0
2,107,1,12,918,800,0
3,2,1,10,88,300,0
4,52,1,12,166,600,0
...,...,...,...,...,...,...
143,83,1,6,0,100,2
144,89,1,6,0,150,2
145,4,1,14,771,450,2
146,35,1,3,98,800,2


In [50]:
y_cls

0      0
1      0
2      0
3      1
4      1
      ..
143    1
144    1
145    0
146    1
147    0
Name: online_order, Length: 148, dtype: int64

In [52]:
from sklearn.model_selection import train_test_split


In [54]:
X_cls_train,X_cls_test,y_cls_train,y_cls_test = train_test_split(X_cls,y_cls,test_size=0.2)
X_reg_train,X_reg_test,y_reg_train,y_reg_test = train_test_split(X_reg,y_reg,test_size=0.2)

In [56]:
from sklearn.linear_model import LogisticRegression,LinearRegression

In [58]:
lr = LogisticRegression()

In [60]:
lr.fit(X_cls_train,y_cls_train)

LogisticRegression()

In [62]:
y_cls_pred = lr.predict(X_cls_test)

In [64]:
y_cls_pred

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1], dtype=int64)

In [66]:
from sklearn.metrics import accuracy_score,r2_score

In [68]:
accuracy_score(y_cls_test,y_cls_pred)

0.8

In [70]:
from sklearn.ensemble import GradientBoostingClassifier,GradientBoostingRegressor,RandomForestClassifier,RandomForestRegressor,AdaBoostRegressor,AdaBoostClassifier

In [72]:
GBC = GradientBoostingClassifier()

In [74]:
GBC.fit(X_cls_train,y_cls_train)

GradientBoostingClassifier()

In [76]:
y_cls_pred = GBC.predict(X_cls_test)

In [78]:
y_cls_pred

array([1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1], dtype=int64)

In [80]:
accuracy_score(y_cls_test,y_cls_pred)

0.7333333333333333

In [82]:
RFC = RandomForestClassifier()

In [84]:
RFC.fit(X_cls_train,y_cls_train)

RandomForestClassifier()

In [86]:
y_cls_pred = RFC.predict(X_cls_test)

In [88]:
y_cls_pred

array([1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1], dtype=int64)

In [90]:
accuracy_score(y_cls_test,y_cls_pred)

0.8333333333333334

In [92]:
AC = AdaBoostClassifier()

In [94]:
AC.fit(X_cls_train,y_cls_train)

AdaBoostClassifier()

In [96]:
y_cls_pred = AC.predict(X_cls_test)

In [98]:
accuracy_score(y_cls_test,y_cls_pred)

0.6666666666666666

In [100]:
from sklearn.tree import DecisionTreeClassifier 
DTC = DecisionTreeClassifier()

In [102]:
DTC.fit(X_cls_train,y_cls_train)

DecisionTreeClassifier()

In [104]:
y_cls_pred = DTC.predict(X_cls_test)

In [106]:
accuracy_score(y_cls_test,y_cls_pred)

0.6666666666666666

In [108]:
LR = LinearRegression()

In [110]:
LR.fit(X_reg_train,y_reg_train)

LinearRegression()

In [112]:
y_reg_pred = LR.predict(X_reg_test)

In [114]:
r2_score(y_reg_test,y_reg_pred)

0.2791744362924351

In [116]:
RFR = RandomForestRegressor()

In [118]:
RFR.fit(X_reg_train,y_reg_train)

RandomForestRegressor()

In [120]:
y_reg_pred = RFR.predict(X_reg_test)

In [122]:
y_reg_pred

array([346.5, 156. , 568. , 564.5, 379.5, 141.5, 581. , 649. , 661. ,
       244. , 616.5, 312.5, 631. , 284. , 297.5, 183. , 284. , 289.5,
       573. , 302.5, 163. , 344.5, 517. , 357.5, 285.5, 631. , 291.5,
       512.5, 390.5, 563.5])

In [124]:
r2_score(y_reg_test,y_reg_pred)

0.4104916485112563

In [127]:
GBR = GradientBoostingRegressor()

In [129]:
GBR.fit(X_reg_test,y_reg_test)

GradientBoostingRegressor()

In [131]:
y_reg_pred = GBR.predict(X_reg_test)

In [133]:
y_reg_pred

array([257.77184544, 168.45628866, 393.11349003, 508.5754531 ,
       602.67034972, 296.02758347, 747.98000452, 453.33377784,
       456.15465208, 394.582744  , 800.89938249, 157.41900909,
       301.40060016, 299.30489951, 476.26333177, 245.80675378,
       206.43649072, 106.26706847, 505.11717745, 152.27619256,
       242.6181395 , 443.29057691, 543.2562143 , 113.58454503,
       397.44335705, 736.04784925, 204.5935008 , 794.0965388 ,
       494.312801  , 800.89938249])

In [135]:
r2_score(y_reg_test,y_reg_pred)

0.998548627827645

In [137]:
AR = AdaBoostRegressor()

In [139]:
AR.fit(X_reg_train,y_reg_train)

AdaBoostRegressor()

In [141]:
y_reg_pred = AR.predict(X_reg_test)

In [143]:
y_reg_test

89     250
117    150
36     400
42     500
37     600
142    300
38     750
13     450
145    450
135    400
2      800
139    150
56     300
108    300
90     500
107    250
133    200
84     100
31     500
51     150
118    250
50     450
28     550
66     100
132    400
53     750
82     200
60     800
70     500
14     800
Name: approx cost, dtype: int64

In [145]:
r2_score(y_reg_test,y_reg_pred)

0.2861630902066541

In [37]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore')
%matplotlib inline


In [39]:
data = pd.read_csv('Zomato-data-.csv')

In [41]:
data

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining


In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    object
 4   votes                        148 non-null    int64 
 5   approx_cost(for two people)  148 non-null    int64 
 6   listed_in(type)              148 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.2+ KB


In [45]:
data.dropna(inplace=True)

In [47]:
data.replace({'online_order':{'Yes':0,'No':1}},inplace=True)

In [49]:
cat = data.select_dtypes(include='object').columns
num = data.select_dtypes(include=['int64','float64']).columns

In [51]:
cat

Index(['name', 'book_table', 'rate', 'listed_in(type)'], dtype='object')

In [53]:
num

Index(['online_order', 'votes', 'approx_cost(for two people)'], dtype='object')

In [55]:
data

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,0,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,0,No,4.1/5,787,800,Buffet
2,San Churro Cafe,0,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,1,No,3.7/5,88,300,Buffet
4,Grand Village,1,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,1,No,3.3/5,0,100,Dining
144,New Indraprasta,1,No,3.3/5,0,150,Dining
145,Anna Kuteera,0,No,4.0/5,771,450,Dining
146,Darbar,1,No,3.0/5,98,800,Dining


In [57]:
num = num.drop(['online_order','approx_cost(for two people)'])

In [59]:
num

Index(['votes'], dtype='object')

In [61]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.ensemble import AdaBoostClassifier,AdaBoostRegressor,GradientBoostingClassifier,GradientBoostingRegressor,RandomForestClassifier,RandomForestRegressor
from xgboost import XGBClassifier,XGBRegressor
from sklearn.metrics import accuracy_score,mean_squared_error,r2_score
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression,LinearRegression
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor

In [63]:
X_cls = data.drop(columns=['online_order'])
y_cls = data[['online_order']]

In [65]:
X_reg = data.drop(columns=['approx_cost(for two people)'])
y_reg = data[['approx_cost(for two people)']]

In [67]:
X_cls_train,X_cls_test,y_cls_train,y_cls_test = train_test_split(X_cls,y_cls,test_size=0.2)
X_reg_train,X_reg_test,y_reg_train,y_reg_test = train_test_split(X_reg,y_reg,test_size=0.2)

In [69]:
num_pipe = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())])


cat_pipe = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('onehot',OneHotEncoder(handle_unknown='ignore'))])

prep_pipe = ColumnTransformer(transformers=[
    ('num',num_pipe,num),
    ('cat',cat_pipe,cat)])


cls = {
    'AdaBoost':AdaBoostClassifier(random_state=42),
    'GradiantBoosting':GradientBoostingClassifier(random_state=42),
    'XGBoost':XGBClassifier(random_state=42,objective='reg:squarederror'),
    'DTC':DecisionTreeClassifier(),
    'LR':LinearRegression(),
    'RFC':RandomForestClassifier(),
    'knn_cl':KNeighborsClassifier(n_neighbors=5,metric='l2'),
    'LR':LogisticRegression()}


reg = {
    'AdaBoost':AdaBoostRegressor(random_state=42),
    'GradiantBoosting':GradientBoostingRegressor(random_state=42),
    'XGBoost':XGBRegressor(random_state=42,objective='reg:squarederror'),
    'LR':LinearRegression(),
    'DTR':DecisionTreeRegressor(),
    'knn_rg':KNeighborsRegressor(n_neighbors=5,metric='l2'),
    'RFR':RandomForestRegressor()}

In [71]:
for name,model in cls.items():
    print('=======')
    pipe = Pipeline(steps=[
    ('preprocessor',prep_pipe),
    ('model',model)
    ])
    pipe.fit(X_cls_train,y_cls_train)
    print('Fitting for',name,'Classification')
    y_pred = pipe.predict(X_cls_test)
    rmse = np.sqrt(mean_squared_error(y_cls_test,y_pred))
    acc = accuracy_score(y_cls_test,y_pred)
    print(f'{name}_rmse = {rmse}')
    print(f'{name}_acc = {acc}')
    print('______________________\n')
    

Fitting for AdaBoost Classification
AdaBoost_rmse = 0.5163977794943222
AdaBoost_acc = 0.7333333333333333
______________________

Fitting for GradiantBoosting Classification
GradiantBoosting_rmse = 0.4472135954999579
GradiantBoosting_acc = 0.8
______________________

Fitting for XGBoost Classification
XGBoost_rmse = 0.4472135954999579
XGBoost_acc = 0.8
______________________

Fitting for DTC Classification
DTC_rmse = 0.48304589153964794
DTC_acc = 0.7666666666666667
______________________

Fitting for LR Classification
LR_rmse = 0.48304589153964794
LR_acc = 0.7666666666666667
______________________

Fitting for RFC Classification
RFC_rmse = 0.408248290463863
RFC_acc = 0.8333333333333334
______________________

Fitting for knn_cl Classification
knn_cl_rmse = 0.3651483716701107
knn_cl_acc = 0.8666666666666667
______________________



In [75]:
for name,model in reg.items():
    print('=======')
    pipe = Pipeline(steps=[
    ('preprocessor',prep_pipe),
    ('model',model)
    ])
    pipe.fit(X_reg_train,y_reg_train)
    print('Fitting for',name,'regressor')
    y_pred = pipe.predict(X_reg_test)
    rmse = np.sqrt(mean_squared_error(y_reg_test,y_pred))
    r2 = r2_score(y_reg_test,y_pred)
    print(f'{name}_rmse = {rmse}')
    print(f'{name}_r2 = {r2}')
    print('______________________\n')
    

Fitting for AdaBoost regressor
AdaBoost_rmse = 190.82905241033038
AdaBoost_r2 = 0.3013397032734564
______________________

Fitting for GradiantBoosting regressor
GradiantBoosting_rmse = 195.52773539069113
GradiantBoosting_r2 = 0.2665106421592215
______________________

Fitting for XGBoost regressor
XGBoost_rmse = 212.10678631257272
XGBoost_r2 = 0.13685011863708496
______________________

Fitting for LR regressor
LR_rmse = 205.28610882002144
LR_r2 = 0.19146988217823235
______________________

Fitting for DTR regressor
DTR_rmse = 253.14686119589422
DTR_r2 = -0.22948198678320209
______________________

Fitting for knn_rg regressor
knn_rg_rmse = 203.58454427256177
knn_rg_r2 = 0.20481773609038578
______________________

Fitting for RFR regressor
RFR_rmse = 205.22128300934094
RFR_r2 = 0.19198044127051794
______________________

